language: php
php:
- 7.0
script:
- find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/wpmktgengine-extension-woocommerce/
