language: php
php:
- 7.0
script:
- find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    tags: true
env:
  global:
  - SVN_REPOSITORY=https://plugins.svn.wordpress.org/wpmktgengine-extension-woocommerce/
  - secure: vTJdA1lsDUBG72m/WBlbh4R2NpBmOOeYiWb4N4kHEPp7VMFcPVX8+qATRITGLxhAWDUbcOBM6Bm5jLuNRK41uz84DktKQoKRd2ud0lv7aEIMmuVGeshAmJyAYYhtJKWrYMZa3aP+QikkXNKtiZF3Tr5ag/oY+2fhU9NFgSZhvBSCq4TcpUl7LzDAuN9fHaQeveKy8UogPPrrBOXuj3/XjArHWmXhCzTSBp7BhFwKgd2WaDDtL9cmjy6EMd2I2cLQax5REY5Yw5iimLkUV2iqMdTD6Gl9xaTqQeODDiDc0u/pYGr/nCJ8sUL/PFq/1Gb3kvKOtZov9D/pSw+T5zVGDrN1S36p23l3a1rrcqQEVL4fhAeJGdgKO2Zs8t5Y1My+Axd7DWqjoh0nOgcTBLjPUXmmmAD1R++Q9zKA6yxTAd/plWqTJJky0x+CGqkpzEcaCsaPIU2WzyDbyjgkSa8Hc05N2Uh5ZeVkK7+YquXoN6IpHnsF5p5rNVcmLXZxZz55YpqCQBZfOH+9iG3xsqB3G3Dx8dER/D9wjvR5gychNDJ3ogq2nBKdbvGFh0ilut2ci3yWIw0cyaOXPofJT0CTgO6zl2dFJwM+Ayp9EoLyYwAUrc/ZjGnQGPA95jzQO83iSYmL9FtrXf0pSjfDmjwS07t9nuhHCtXszdEt0731bGM=
  - secure: KQ/Y6Ax8N5eNw5gMUjKvQLAXf3UVkY5y4AvAnaX1ZZ2k06jDi5Mo2mHSTkB6CqW8G8ZNiZlb2OnjK/QOoYurA593iUnaUOTJQTvJJWxTC5ouDqPH+2fi4w4T/sIzMgaowsNPcp5j/CytlmllI2okhLfBM131/DWG7v3t09jnPj7mNymVFTwKxTzoI34w3r01j+OJ60mRUVwbrWxPwRrBM1wKoEJoBht1U967r+C8TZx/t4ha5yivWYzxIbP+tTJe/TVRn3GMdhFxKK22XBK/ibf1ujbYdLCQuOAtjjMk4ZVGmSwbaeQnaEQ8dTFxTQQ5YTOMMVgiuSG/np1z4fT9vae/NmAfjqOUH2DJoWKjUHozP9Yf72jZ7/urAsaTO3VkQhuouuXQ8xcxKoLTgmmVkncnCQjQwsb1kZ5VnXN9ozyEcS9aq9amZEocm5LlZGV4Ymw8ukFOTbYc5+ucNsxLoMsUQbV3+jtKLjt5N3WL7IIlxQ2wKnCmCbMmAdP+3NQ9n7nn8KIzj+OdJIZsp2ZXuN3a9FjaZYRG/lPLTgrjTG8VBB891fHV167WcVsS4w2gncjhLTE4nqdYSuWvU/ZLrNO76gJBToZTZJ3SSISfMI/BhEJKd1t7RLyGWt7whXNNqQVcyJ7O1FfJNW/ivIm+nuX52ShKEia+Dg0FDvD44Ks=
