name: Deployed to WordPress
on:
  push:
    tags:        
      - '*'
  workflow_call:
jobs:
  linted:
    name: PHP Syntax Error Free
    runs-on: ubuntu-latest
    steps:
      - name: Check PHP Errors
        run: |
          find . -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
  deploy:
    name: Deploy to WordPress.org Plugin Repository
    needs: linted
    runs-on: ubuntu-latest
    env:
      SVN_REPOSITORY: https://plugins.svn.wordpress.org/wpmktgengine-extension-woocommerce/
      SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
      SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Variables
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Setup Variables - Test
        run: |
          echo $SOURCE_NAME
          echo $SOURCE_BRANCH
          echo $SOURCE_TAG
        env:
          SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
          SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      - name: Deploy to SVN
        run: |
          sh ./deploy/deploy.sh
        env:
          TRAVIS_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
  slack:
    name: Slack Notification
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: GenooBot
          SLACK_ICON: https://avatars.githubusercontent.com/u/50386665?s=200&v=4
          SLACK_TITLE: WordPress Plugin - WooCommerce
          SLACK_MESSAGE: Deployment Successful
          MSG_MINIMAL: true
