name: Manually Deploy New Version
on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to WordPress.org Plugin Repository
    runs-on: ubuntu-latest
    env:
      SVN_REPOSITORY: https://plugins.svn.wordpress.org/wpmktgengine-extension-woocommerce/
      SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
      SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: master
      - name: Run Increment Function
        run: |
          yes "" | bash ./deploy/increment.sh
